[web_server]
web-server ansible_host=127.0.0.1 ansible_port=2222 ansible_user=root ansible_ssh_pass=root ansible_connection=ssh

[mysql_db]
mysql-db ansible_host=127.0.0.1 ansible_connection=docker

[all:vars]
project_root=/app/demo
db_name=A-NETH_Tithyarita-db
db_user=root
db_pass=Hello@123
backup_dir=/root/backups
